name: Package

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t myflask .

    - name: Save Docker image as tar
      run: |
        docker save myflask -o myflask.tar

    - name: Upload Docker image
      uses: actions/upload-artifact@v2
      with:
        name: myflask-docker-image
        path: myflask.tar
